
require '技能.野怪技能'
-- require '技能.野怪光环'
require '技能.英雄技能'
require '技能.成就'
-- require '技能.新光环'
require '技能.buff'
require '技能.技能总览'
require '技能._常用'
require '技能.宠物天赋'
require '技能.英雄天赋'
require '技能.英雄技能2'